### ISSUE TITLE
Checklist polygon for Yellowstone Northern Range (Frog Rock; YELL) needs correction

### ISSUE THREAD

**Issue by nfranz** [BioKIC/NEON-Biorepository-Data-Docs#1]
See title. NEON BioRepo polygon is incorrect, too large; resulting in too many external records relative to actual NEON site.

Per NEON: BioRepo:
https://biorepo.neonscience.org/portal/collections/map/index.php?clid=97&cltype=vouchers&taxonfilter=&db=all&type=1&reset=1

Per NEON:
https://www.neonscience.org/field-sites/field-sites-map/YELL

**Comment by arbolitoloco** [comment]
The polygon available at the .txt was indeed the corrected one, thanks for catching that. I have updated it at the Plants checklist, will do the same for other taxa, but don't know what happens to taxa/vouchers that might have been "incorrectly" associated with that polygon. Maybe @egbot can advise?
