### ISSUE TITLE
Cannot batch determine based on NEON Sample ID

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository-Data-Docs#12]
batch update tool only works on catalog number (I think) and did not match on secondary identifiers when I tried to add determinations using neon Sample Tags

**Comment by mandrewj** [comment]
Probably should have posted this to the portal proper - and did so secondarily at: 
https://github.com/BioKIC/NEON-Biorepository/issues/72

Leaving here because it affects data quality, and perhaps there is a data-management solution instead of a programmatic one.

**Comment by arbolitoloco** [comment]
Closed by https://github.com/BioKIC/NEON-Biorepository/commit/32a16ce1f47996e3cbb591b143876ed95c5998d7
