### ISSUE TITLE
Taxonomy issues in Aquatic Plant Point Count Taxonomy Collection

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository-Data-Docs#14]
The aquatic plant point count taxonomy collection has some strange taxonomy issues. It says there is only 1 family, but then lists four.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/4763928/66184457-f5e8bc80-e630-11e9-8f05-a46424432ffe.png">

**Several specimens are "determined" as their morphospecies name:**
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/4763928/66183901-43fcc080-e62f-11e9-8c68-3fe301f7dc06.png">

**Others are given sci names or undetermined:** <Can't click on sci names though>
<img width="975" alt="image" src="https://user-images.githubusercontent.com/4763928/66183952-6262bc00-e62f-11e9-885f-c500e35d8dd9.png">

**Collection more info page:** 
https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=7&stat=taxonomy#taxonomystats

**All specimens in the collection:**
https://biorepo.neonscience.org/portal/collections/list.php?db=7&reset=1&country=USA&state=&county=

**Comment by arbolitoloco** [comment]
The stats just were out of date. You can update statistics for a given collection in the collection management options in Symbiota.

**Comment by arbolitoloco** [comment]
The species determined with their codes is a normal expected behavior by the occurrence harvester. Still in the works to correctly assign taxa to them.
Undetermined also normal.
Closing the issue as it's a non-issue for now.
