### ISSUE TITLE
Belowground Biomass Collection Dates not harvesting

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository-Data-Docs#18]
Via Laura S. from 11/5/19 meeting.

Dates not harvesting for Belowground Biomass Collection samples. 

Via Ed:
Will be available in 2 months from API but if we need it sooner then need to download from the data portal and upload.

--> Seems like at this point we can wait, but I'm placing here so that if it doesn't get exposed in API in next couple of months, we don't forget the issue.

**Comment by arbolitoloco** [comment]
Related to #6

**Comment by kyule** [comment]
Will import from R if someone expresses interest. Otherwise, wait until API improvements occur.

**Comment by kyule** [comment]
All samples now have eventDates.  API update fixed the issue.
