### ISSUE TITLE
Fill in missing and add additional available small mammal data

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository-Data-Docs#20]
Fill all holes possible in small mammal data (taxon) and fill additional fields (e.g. sex, reproductive status, preparation) based on available data in the NEON data product "DP1.10072.001" using Full Text File Import. Collections NEON-MBSC, NEON-MABC, NEON-METC, NEON-MFSC, NEON-MHSC, NEON-MAVC 

e.g. an updated blood sample occurence record 
<img width="944" alt="image" src="https://user-images.githubusercontent.com/4763928/68261426-58045b00-fffd-11e9-8ddf-1f0e467bc806.png">

**Comment by kyule** [comment]
Made an R code to link neon trap event to biorepo sample and grab and format fields in neon data product for symbiota. Then used full text file import in specimen management.

**Comment by arbolitoloco** [comment]
Please @kyule upload R script to this repo or make it available somehow in our internal workflows folder.

**Comment by kyule** [comment]
All codes have been available in the NEON Biorepository google drive (Data Codes / Collection Summary / ). I will want to better comment them and make them independent of directory in order to post here

**Comment by kyule** [comment]
Here is a zip file of the code Mammals_PortalUpdatesDataIssues.R, necessary input files, and output files used to get spp IDs, input additional value-added details, and identify mammal capture data issues in the main NEON data portal. Note that codes used to generate specific sample lists for individual loan requests are in the NEON Biorepository Google Drive but won't be posted here. 
[Mammal_portalUpdateDataIssues.zip](https://github.com/BioKIC/NEON-Biorepository-Data-Docs/files/3825892/Mammal_portalUpdateDataIssues.zip)

**Comment by nfranz** [comment]
Thank you, Kelsey!

   Amazing value added allowing us to understand the complexity of issues.

Nico

**Comment by kyule** [comment]
Updated based on Adding NEON mammal capture data to the Biorepository Data Portal tutorial in drive
