### ISSUE TITLE
Sample Class ptx_taxonomy_in.slideID not able to harvest

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository-Data-Docs#3]
The sample class ptx_taxonomy_in.slideID (for which we already have 1335 samples) is not available via the API (presumably).

We have a problem for NEON - they are not exposing some sample classes to the API which are sent to us.  This is at least true for the ptx_taxonomy_in.slideID sample class.
An example: If you look at this parent sample CUPE.20170629.EPILITHON.4 in the API and check the child samples: curl -X GET --header ‘Accept: application/json’ ’https://data.neonscience.org/api/v0/samples/view?sampleTag=CUPE.20170629.EPILITHON.4&sampleClass=alg_domainLab_in.sampleIDtaxonomy'
Then you will find that it, indeed, does have a child ‘CUPE.20170629.EPILITHON.4 - SLIDE - A’ which was sent to us on manifest: https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=513

However, the API does not give any hits when using that child identifier with the appropriate sample class: 
curl -X GET --header ‘Accept: application/json’ ’https://data.neonscience.org/api/v0/samples/view?sampleTag=CUPE.20170629.EPILITHON.4%20-%20FRACTION%20-%20A&sampleClass=ptx_taxonomy_in.slideID'
Also, that sample type is not in the supported sample classes listed on the sample viewer page, either

Take home:
CUPE.20170629.epilithon.4 - slide - a exists in the NEON database and has sample class ptx_taxonomy_in.slideID (as seen in the children of its parent) but the API will not resolve to the sample when given that combination.

**Comment by arbolitoloco** [comment]
Attempted reharvesting the shipment mentioned above (https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=513), still failing on sample class and tag. Please open a ServiceNow request to add those samples to NEON's API.

**Comment by kyule** [comment]
The remaining shipment that could not be harvested now has been without issue. The only remaining samples that are not harvesting, shouldn't be: opal samples and samples that have been discarded.
