### ISSUE TITLE
Home page - login link blocked by banner on Safari

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository-Data-Docs#37]
See the attached screenshot.  On Safari the 'Discover and access sample-based data' banner covers the login/account/sitemap links unless you have the screen space to extend the window very wide.

Likely there needs to be extra spacing there?
<img width="1383" alt="Screen Shot 2020-01-08 at 11 17 37 AM" src="https://user-images.githubusercontent.com/6679254/72004922-a86c8480-3209-11ea-94be-dc11e8d770ed.png">

**Comment by arbolitoloco** [comment]
Not a banner issue, but a innertext conteiner issue. Will fix.
