### ISSUE TITLE
Sample listing on manifests - font too large

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository-Data-Docs#38]
The sample table extends off-screen, even when stretched very wide.  The inner margins of the text/cells in the table also could probably be adjusted.

Using Chrome on a Mac, duplicated with Safari on the same mac.
<img width="1598" alt="Screen Shot 2020-01-08 at 2 57 04 PM" src="https://user-images.githubusercontent.com/6679254/72019589-3c991480-3227-11ea-82f6-fdad32ea707c.png">

**Comment by arbolitoloco** [comment]
Closed by https://github.com/BioKIC/NEON-Biorepository/commit/f72ac566eb2a6062a41fdbb431927ce59860e7a7
