### ISSUE TITLE
Individual Count (=Specimen Count) not harvested for carabid tubes

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository-Data-Docs#48]
For samples of sampleClass: bet_sorting_in.subsampleID.bet
The API returns a numeric value for a field (sms_value) called 'specimen_count'
This should be harvested into the "individual count" field within symbiota.

For samples of sampleClass: bet_archivepooling_in.subsampleID.bet
The API returns sample UUIDs for parent samples, a full individual count for this class would require summing the individual counts for all listed parents.  Presumably there should always be multiple parent samples for any single pooled sample - from 2 to 4 parents, supposedly.

These data would enrich the biorepo portal and would allow researchers to gain true individual counts without having to go through the main NEON data packages.

**Comment by kyule** [comment]
Unclear whether we should use these data as they represent the total no. of carabids from the cup rather than the number in the tube.
