### ISSUE TITLE
Locality details failed to populated for many of Belowground Biomass Collection (Megapit)

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository-Data-Docs#53]
Failed locality harvest: Belowground Biomass Collection (Megapit) (NEON-BBSC-MP)

Researchers are now asking about these samples, but because there are no taxa or georeferences they are unable to use the portal to view them without downloading the entire collection from the more info page.

Collection dates also not available for this collection.

**Comment by arbolitoloco** [comment]
This might be related to #54

**Comment by arbolitoloco** [comment]
Please open ServiceNow Request to include locality information in the NEON API
