### ISSUE TITLE
Carabid DNA collection not harvesting locality

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository-Data-Docs#77]
The carabid DNA extract collection:
https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=63

is not harvesting the locality for the samples.  They are all listed with the locality "Carnegie Museum of Natural History" - which is not their collection location.  Moreover, there is no Country/State/County or GPS data for these records.  This is likely a harvesting code issue, but it could also be because these data are not available in the API?

Either way, the locality should be stripped and the code should be augmented to not put that into the locality in the future.

**Comment by kyule** [comment]
This is related to issue https://github.com/BioKIC/NEON-Biorepository/issues/142

**Comment by kyule** [comment]
Can be closed due to fixes from Ed based on using the sample hierarchy.
