### ISSUE TITLE
Need to move all samples of class mam_pertrapnight_in.earSampleID in shipment CCDB-2019-048 from collection  NEON-MAMC-EA

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository-Data-Docs#85]
All samples in the shipment CCDB-2019-048 and all future CCDB shipments are **DNA samples** and therefore all mammal samples therein should be published in collection Mammal Collection (DNA Extracts) (NEON-MAMC-DNA)

Unfortunately, these mammal ear punches and associated DNA samples are given the same sampleClass (mam_pertrapnight_in.earSampleID) and are therefore being published in collection Mammal Collection (Ear Tissue)  (NEON-MAMC-EA). These are not ear punches and now the collection contains both physical tissue samples and DNA samples. 

Kelsey is putting in a service now request about this sample class issue, but until (if ever) that is fixed we cannot publish the samples this way.

**Comment by kyule** [comment]
Katie has opened a service now request on this. She provided a spreadsheet indicating that all samples on the sheet need to be in the DNA collection and not the earr tissue collection.
[MammalDNAsamples.xlsx](https://github.com/BioKIC/NEON-Biorepository-Data-Docs/files/5430932/MammalDNAsamples.xlsx)

**Comment by arbolitoloco** [comment]
I've moved the 2729 occurrences associated with this shipment from [Mammal Collection (Ear Tissue)](https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=25) to [Mammal Collection (DNA Extracts](https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=71). For reference, I'm attaching a csv with the modified occurrences. 
🧾 [CCDB-2019-048-records-moved-from-mam-ea.xlsx](https://github.com/BioKIC/NEON-Biorepository-Data-Docs/files/5441298/CCDB-2019-048-records-moved-from-mam-ea.xlsx)

However, the excel file attached contains 6348 catalog numbers, so I believe this might be another issue entirely, @kyule might want to check.
