### ISSUE TITLE
Mammal and Fish DNA sample class updates,  manifest and sampleClass mapping

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository-Data-Docs#88]
Katie LeVan has asked that we **update manifest** [CCDB-2019-048](https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=899) as follows:

**Parent (existing) classes:**
Sample class for fish fin clips: fsh_perFish_in.dnaSampleID (not generally archived)
Sample class for mammal ear tissue: mam_pertrapnight_in.earSampleID

**New classes:** 
Sample class for aqueous fish DNA extract: mam_barcoding_in.dnaSubsampleID.fsh (FISC-DNA)
Sample class for aqueous mammal DNA extract: mam_barcoding_in.dnaSubsampleID.mam (MAMC-DNA)

**These new sample classes should then be mapped to the following two collections, respectively:** 
Fish Collection (DNA Extracts)(NEON-FISC-DNA)
Mammal Collection (DNA Extracts)(NEON-MAMC-DNA)

**Comment by arbolitoloco** [comment]
- [x] 546 records updated (`fsh_perFish_in.dnaSampleID` -> `mam_barcoding_in.dnaSubsampleID.fsh`);

- [x] 2729 records updated (`mam_pertrapnight_in.earSampleID` -> `mam_barcoding_in.dnaSubsampleID.mam`).
