### ISSUE TITLE
Occurrence harvests not pulling correct IDs for bulk samples

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository-Data-Docs#95]
We have around 1000 new invertebrate bycatch samples that have 'IB' as the taxon name, and not 'Bulk Terrestrial invertebrates' as it should be

**Comment by arbolitoloco** [comment]
@egbot the stored procedure defined for pseudotaxa only works with samples that have returned null `sciname` after harvesting. For some reason, these specimens are being assigned 'IB' as their sciname during harvesting. I'd suggest that the Occurrence Harvester should be modified to avoid this. For now, I'm calling another stored procedure that replaces the scinames instead.
